import type { FoodItem } from '@/types'

// Composite dishes, sandwiches, fast-food combos, breakfast items, etc.
// Macros are reasonable per-serving estimates for the WHOLE dish (per: 'item').
// `defaultQty` is the typical serving weight in grams.
// Anyone obsessing over precision can `Teach` a custom version with exact numbers.
export const COMPOSITE_FOODS: FoodItem[] = [
  // ── Sandwiches ───────────────────────────────────────────────────────────
  { id: 'sandwich-chicken-mayo', name: 'Chicken Mayo Sandwich', aliases: ['chicken mayo', 'chicken mayo sarmie', 'chicken sandwich', 'chicken mayo toasted'], per: 'item', kcal: 450, protein: 28, carbs: 38, fat: 20, defaultQty: 230 },
  { id: 'sandwich-bacon-avo-feta', name: 'Bacon Avo Feta Sandwich', aliases: ['bacon avo feta', 'baf sandwich', 'bacon avo feta sarmie', 'baf sarmie'], per: 'item', kcal: 580, protein: 24, carbs: 36, fat: 38, defaultQty: 280 },
  { id: 'sandwich-bacon-egg', name: 'Bacon & Egg Sandwich', aliases: ['bacon egg sandwich', 'bacon and egg sandwich', 'bacon egg sarmie'], per: 'item', kcal: 480, protein: 22, carbs: 32, fat: 28, defaultQty: 230 },
  { id: 'sandwich-egg-mayo', name: 'Egg Mayo Sandwich', aliases: ['egg mayo', 'egg mayo sarmie', 'egg salad sandwich'], per: 'item', kcal: 410, protein: 18, carbs: 32, fat: 24, defaultQty: 220 },
  { id: 'sandwich-tuna-mayo', name: 'Tuna Mayo Sandwich', aliases: ['tuna mayo', 'tuna sandwich', 'tuna sarmie', 'tuna mayo sarmie'], per: 'item', kcal: 420, protein: 26, carbs: 34, fat: 20, defaultQty: 225 },
  { id: 'sandwich-cheese-tomato', name: 'Cheese & Tomato Sandwich', aliases: ['cheese tomato sandwich', 'cheese and tomato'], per: 'item', kcal: 340, protein: 14, carbs: 36, fat: 16, defaultQty: 195 },
  { id: 'sandwich-cheese', name: 'Cheese Sandwich', aliases: ['cheese sarmie', 'cheese toastie', 'cheese toasted'], per: 'item', kcal: 380, protein: 14, carbs: 34, fat: 20, defaultQty: 165 },
  { id: 'sandwich-ham-cheese', name: 'Ham & Cheese Sandwich', aliases: ['ham cheese sandwich', 'ham and cheese', 'ham cheese sarmie', 'ham cheese toastie'], per: 'item', kcal: 430, protein: 24, carbs: 34, fat: 22, defaultQty: 200 },
  { id: 'sandwich-blt', name: 'BLT', aliases: ['blt sandwich', 'bacon lettuce tomato'], per: 'item', kcal: 520, protein: 22, carbs: 38, fat: 30, defaultQty: 250 },
  { id: 'sandwich-club', name: 'Club Sandwich', aliases: ['club sarmie', 'triple decker'], per: 'item', kcal: 680, protein: 36, carbs: 52, fat: 32, defaultQty: 380 },
  { id: 'sandwich-steak', name: 'Steak Sandwich', aliases: ['steak sarmie', 'steak roll'], per: 'item', kcal: 620, protein: 38, carbs: 46, fat: 28, defaultQty: 320 },
  { id: 'sandwich-chicken-tikka', name: 'Chicken Tikka Sandwich', aliases: ['chicken tikka sarmie', 'tikka sandwich'], per: 'item', kcal: 470, protein: 30, carbs: 40, fat: 18, defaultQty: 240 },
  { id: 'sandwich-veggie', name: 'Veggie Sandwich', aliases: ['vegetable sandwich', 'veg sarmie', 'salad sandwich'], per: 'item', kcal: 310, protein: 10, carbs: 42, fat: 12, defaultQty: 230 },
  { id: 'sandwich-peanut-butter', name: 'Peanut Butter Sandwich', aliases: ['pb sandwich', 'pb sarmie', 'peanut butter sarmie'], per: 'item', kcal: 360, protein: 12, carbs: 38, fat: 18, defaultQty: 90 },
  { id: 'sandwich-pbj', name: 'PB&J Sandwich', aliases: ['pbj', 'peanut butter and jelly', 'peanut butter jam', 'pb and j'], per: 'item', kcal: 390, protein: 12, carbs: 50, fat: 16, defaultQty: 110 },
  { id: 'sandwich-marmite', name: 'Marmite Sandwich', aliases: ['marmite sarmie', 'marmite toast'], per: 'item', kcal: 220, protein: 8, carbs: 32, fat: 6, defaultQty: 80 },
  { id: 'sandwich-toastie', name: 'Toastie', aliases: ['toasted sandwich', 'jaffle'], per: 'item', kcal: 400, protein: 16, carbs: 36, fat: 22, defaultQty: 180 },
  { id: 'sandwich-chicken-mayo-avo', name: 'Chicken, Mayo & Avo Sandwich', aliases: ['chicken mayo avo', 'chicken avo mayo sarmie'], per: 'item', kcal: 540, protein: 30, carbs: 38, fat: 28, defaultQty: 260 },
  { id: 'sandwich-cheese-ham-tomato', name: 'Cheese, Ham & Tomato Sandwich', aliases: ['cheese ham tomato', 'ham cheese tomato sarmie'], per: 'item', kcal: 460, protein: 24, carbs: 36, fat: 24, defaultQty: 230 },
  { id: 'wrap-chicken', name: 'Chicken Wrap', aliases: ['chicken tortilla wrap', 'chicken wrap'], per: 'item', kcal: 480, protein: 32, carbs: 42, fat: 18, defaultQty: 260 },
  { id: 'wrap-chicken-mayo', name: 'Chicken Mayo Wrap', aliases: ['chicken mayo wrap'], per: 'item', kcal: 540, protein: 30, carbs: 40, fat: 26, defaultQty: 270 },
  { id: 'wrap-beef', name: 'Beef Wrap', aliases: ['beef wrap', 'steak wrap'], per: 'item', kcal: 540, protein: 32, carbs: 44, fat: 24, defaultQty: 290 },
  { id: 'wrap-veggie', name: 'Veggie Wrap', aliases: ['vegetable wrap', 'veg wrap', 'salad wrap'], per: 'item', kcal: 360, protein: 12, carbs: 48, fat: 14, defaultQty: 260 },
  { id: 'wrap-falafel', name: 'Falafel Wrap', aliases: ['falafel wrap'], per: 'item', kcal: 470, protein: 16, carbs: 56, fat: 22, defaultQty: 290 },

  // ── Burgers ───────────────────────────────────────────────────────────────
  { id: 'burger-cheese', name: 'Cheeseburger', aliases: ['cheese burger'], per: 'item', kcal: 540, protein: 27, carbs: 42, fat: 28, defaultQty: 220 },
  { id: 'burger-bacon', name: 'Bacon Burger', aliases: ['bacon cheeseburger'], per: 'item', kcal: 640, protein: 32, carbs: 42, fat: 38, defaultQty: 250 },
  { id: 'burger-double', name: 'Double Burger', aliases: ['double cheeseburger', 'double cheese burger'], per: 'item', kcal: 760, protein: 42, carbs: 44, fat: 44, defaultQty: 300 },
  { id: 'burger-chicken', name: 'Chicken Burger', aliases: ['chicken burger', 'crispy chicken burger'], per: 'item', kcal: 520, protein: 28, carbs: 48, fat: 24, defaultQty: 240 },
  { id: 'burger-veggie', name: 'Veggie Burger', aliases: ['vegetarian burger', 'plant burger'], per: 'item', kcal: 380, protein: 18, carbs: 44, fat: 14, defaultQty: 220 },
  { id: 'burger-bigmac', name: 'Big Mac', aliases: ['big mac mcdonalds'], per: 'item', kcal: 563, protein: 26, carbs: 45, fat: 33, defaultQty: 219 },
  { id: 'burger-whopper', name: 'Whopper', aliases: ['burger king whopper'], per: 'item', kcal: 657, protein: 28, carbs: 49, fat: 40, defaultQty: 290 },
  { id: 'burger-mcdo-quarter', name: 'Quarter Pounder', aliases: ['quarter pounder with cheese', 'quarter pounder'], per: 'item', kcal: 520, protein: 30, carbs: 42, fat: 26, defaultQty: 200 },
  { id: 'slider', name: 'Slider', aliases: ['mini burger', 'sliders'], per: 'item', kcal: 240, protein: 12, carbs: 18, fat: 13, defaultQty: 100 },

  // ── Breakfast ─────────────────────────────────────────────────────────────
  { id: 'breakfast-english', name: 'Full English Breakfast', aliases: ['english breakfast', 'full english', 'fry up'], per: 'item', kcal: 850, protein: 38, carbs: 50, fat: 56, defaultQty: 500 },
  { id: 'breakfast-bacon-eggs', name: 'Bacon & Eggs', aliases: ['bacon and eggs'], per: 'item', kcal: 380, protein: 24, carbs: 2, fat: 30, defaultQty: 200 },
  { id: 'breakfast-scrambled-eggs', name: 'Scrambled Eggs', aliases: ['scrambled egg'], per: 'item', kcal: 220, protein: 14, carbs: 2, fat: 16, defaultQty: 140 },
  { id: 'breakfast-fried-eggs', name: 'Fried Eggs', aliases: ['fried egg', '2 fried eggs'], per: 'item', kcal: 180, protein: 13, carbs: 1, fat: 14, defaultQty: 120 },
  { id: 'breakfast-poached-eggs', name: 'Poached Eggs', aliases: ['poached egg'], per: 'item', kcal: 150, protein: 12, carbs: 1, fat: 10, defaultQty: 110 },
  { id: 'breakfast-omelette', name: 'Omelette', aliases: ['omelet', 'plain omelette'], per: 'item', kcal: 280, protein: 18, carbs: 2, fat: 22, defaultQty: 160 },
  { id: 'breakfast-omelette-cheese', name: 'Cheese Omelette', aliases: ['cheese omelet'], per: 'item', kcal: 410, protein: 24, carbs: 3, fat: 34, defaultQty: 200 },
  { id: 'breakfast-omelette-ham-cheese', name: 'Ham & Cheese Omelette', aliases: ['ham cheese omelette', 'ham cheese omelet'], per: 'item', kcal: 460, protein: 28, carbs: 3, fat: 36, defaultQty: 230 },
  { id: 'breakfast-pancake-stack', name: 'Pancake Stack', aliases: ['pancakes', '3 pancakes', 'pancake stack'], per: 'item', kcal: 530, protein: 12, carbs: 78, fat: 18, defaultQty: 300 },
  { id: 'breakfast-waffles', name: 'Waffles', aliases: ['waffle', 'belgian waffle'], per: 'item', kcal: 460, protein: 10, carbs: 56, fat: 22, defaultQty: 200 },
  { id: 'breakfast-french-toast', name: 'French Toast', aliases: ['eggy bread'], per: 'item', kcal: 420, protein: 14, carbs: 44, fat: 20, defaultQty: 200 },
  { id: 'breakfast-oats-bowl', name: 'Bowl of Oats', aliases: ['oats bowl', 'porridge bowl', 'morning oats'], per: 'item', kcal: 320, protein: 12, carbs: 54, fat: 6, defaultQty: 280 },
  { id: 'breakfast-overnight-oats', name: 'Overnight Oats', aliases: ['overnight oats'], per: 'item', kcal: 380, protein: 14, carbs: 60, fat: 9, defaultQty: 320 },
  { id: 'breakfast-cereal-bowl', name: 'Bowl of Cereal', aliases: ['cereal', 'corn flakes bowl', 'cereal with milk'], per: 'item', kcal: 230, protein: 9, carbs: 42, fat: 4, defaultQty: 240 },
  { id: 'breakfast-muesli', name: 'Bowl of Muesli', aliases: ['muesli'], per: 'item', kcal: 360, protein: 10, carbs: 56, fat: 11, defaultQty: 220 },
  { id: 'breakfast-granola', name: 'Bowl of Granola', aliases: ['granola', 'granola with milk'], per: 'item', kcal: 400, protein: 10, carbs: 60, fat: 14, defaultQty: 200 },
  { id: 'breakfast-yogurt-granola', name: 'Yogurt & Granola', aliases: ['yogurt granola', 'greek yogurt granola', 'yogurt and granola'], per: 'item', kcal: 360, protein: 18, carbs: 48, fat: 10, defaultQty: 280 },
  { id: 'breakfast-yogurt-fruit', name: 'Yogurt & Fruit', aliases: ['yogurt fruit', 'yogurt and fruit'], per: 'item', kcal: 220, protein: 12, carbs: 32, fat: 4, defaultQty: 250 },
  { id: 'breakfast-smoothie-bowl', name: 'Smoothie Bowl', aliases: ['acai bowl'], per: 'item', kcal: 380, protein: 10, carbs: 64, fat: 9, defaultQty: 400 },
  { id: 'breakfast-toast-butter', name: 'Toast with Butter', aliases: ['buttered toast', 'toast and butter'], per: 'item', kcal: 130, protein: 3, carbs: 16, fat: 6, defaultQty: 45 },
  { id: 'breakfast-toast-jam', name: 'Toast with Jam', aliases: ['toast jam', 'jam on toast'], per: 'item', kcal: 140, protein: 3, carbs: 24, fat: 3, defaultQty: 50 },
  { id: 'breakfast-toast-avo', name: 'Avo on Toast', aliases: ['avocado toast', 'avo toast'], per: 'item', kcal: 260, protein: 7, carbs: 24, fat: 16, defaultQty: 130 },
  { id: 'breakfast-toast-pb', name: 'Peanut Butter Toast', aliases: ['pb toast', 'peanut butter on toast'], per: 'item', kcal: 280, protein: 10, carbs: 26, fat: 14, defaultQty: 65 },
  { id: 'breakfast-eggs-bacon-toast', name: 'Eggs, Bacon & Toast', aliases: ['eggs bacon toast', 'bacon eggs toast'], per: 'item', kcal: 560, protein: 28, carbs: 36, fat: 32, defaultQty: 330 },
  { id: 'breakfast-bagel-cream-cheese', name: 'Bagel with Cream Cheese', aliases: ['bagel cream cheese', 'bagel'], per: 'item', kcal: 380, protein: 12, carbs: 56, fat: 12, defaultQty: 130 },
  { id: 'breakfast-croissant', name: 'Croissant', aliases: ['plain croissant'], per: 'item', kcal: 280, protein: 6, carbs: 31, fat: 14, defaultQty: 60 },
  { id: 'breakfast-croissant-ham-cheese', name: 'Ham & Cheese Croissant', aliases: ['ham cheese croissant'], per: 'item', kcal: 430, protein: 18, carbs: 32, fat: 26, defaultQty: 120 },
  { id: 'breakfast-banana-toast', name: 'Banana on Toast', aliases: ['banana toast'], per: 'item', kcal: 220, protein: 5, carbs: 42, fat: 4, defaultQty: 165 },
  { id: 'breakfast-protein-shake', name: 'Protein Shake', aliases: ['protein smoothie'], per: 'item', kcal: 220, protein: 30, carbs: 12, fat: 4, defaultQty: 350 },

  // ── Pasta dishes ──────────────────────────────────────────────────────────
  { id: 'pasta-bolognese', name: 'Spaghetti Bolognese', aliases: ['spag bol', 'bolognese', 'pasta bolognese', 'spaghetti bolognaise'], per: 'item', kcal: 620, protein: 30, carbs: 70, fat: 22, defaultQty: 400 },
  { id: 'pasta-carbonara', name: 'Spaghetti Carbonara', aliases: ['carbonara', 'pasta carbonara'], per: 'item', kcal: 680, protein: 28, carbs: 68, fat: 30, defaultQty: 380 },
  { id: 'pasta-alfredo', name: 'Pasta Alfredo', aliases: ['fettuccine alfredo', 'alfredo'], per: 'item', kcal: 720, protein: 22, carbs: 70, fat: 38, defaultQty: 400 },
  { id: 'pasta-chicken-alfredo', name: 'Chicken Alfredo', aliases: ['chicken alfredo'], per: 'item', kcal: 820, protein: 42, carbs: 70, fat: 40, defaultQty: 450 },
  { id: 'pasta-pesto', name: 'Pasta Pesto', aliases: ['pesto pasta'], per: 'item', kcal: 580, protein: 16, carbs: 70, fat: 24, defaultQty: 380 },
  { id: 'pasta-arrabbiata', name: 'Pasta Arrabbiata', aliases: ['arrabbiata', 'tomato pasta'], per: 'item', kcal: 480, protein: 14, carbs: 78, fat: 12, defaultQty: 380 },
  { id: 'pasta-mac-cheese', name: 'Mac & Cheese', aliases: ['mac and cheese', 'macaroni cheese'], per: 'item', kcal: 620, protein: 22, carbs: 64, fat: 28, defaultQty: 350 },
  { id: 'pasta-lasagna', name: 'Lasagna', aliases: ['lasagne', 'beef lasagna'], per: 'item', kcal: 580, protein: 28, carbs: 50, fat: 28, defaultQty: 350 },
  { id: 'pasta-tuna', name: 'Tuna Pasta', aliases: ['tuna pasta', 'pasta tuna'], per: 'item', kcal: 540, protein: 28, carbs: 70, fat: 14, defaultQty: 400 },
  { id: 'pasta-prawn', name: 'Prawn Pasta', aliases: ['shrimp pasta', 'prawn linguine'], per: 'item', kcal: 560, protein: 30, carbs: 68, fat: 16, defaultQty: 400 },

  // ── Pizza ─────────────────────────────────────────────────────────────────
  { id: 'pizza-margherita', name: 'Margherita Pizza', aliases: ['margherita pizza', 'cheese pizza'], per: 'item', kcal: 760, protein: 30, carbs: 96, fat: 26, defaultQty: 320 },
  { id: 'pizza-pepperoni', name: 'Pepperoni Pizza', aliases: ['pepperoni pizza', 'salami pizza'], per: 'item', kcal: 880, protein: 36, carbs: 90, fat: 38, defaultQty: 340 },
  { id: 'pizza-hawaiian', name: 'Hawaiian Pizza', aliases: ['ham pineapple pizza'], per: 'item', kcal: 820, protein: 34, carbs: 92, fat: 32, defaultQty: 340 },
  { id: 'pizza-vegetarian', name: 'Vegetarian Pizza', aliases: ['veggie pizza', 'vegetable pizza'], per: 'item', kcal: 720, protein: 26, carbs: 92, fat: 24, defaultQty: 340 },
  { id: 'pizza-meat-lovers', name: 'Meat Lovers Pizza', aliases: ['meat lovers'], per: 'item', kcal: 980, protein: 42, carbs: 88, fat: 48, defaultQty: 360 },
  { id: 'pizza-bbq-chicken', name: 'BBQ Chicken Pizza', aliases: ['bbq chicken pizza'], per: 'item', kcal: 860, protein: 38, carbs: 100, fat: 30, defaultQty: 350 },
  { id: 'pizza-slice-pepperoni', name: 'Pepperoni Pizza Slice', aliases: ['slice pepperoni'], per: 'item', kcal: 300, protein: 13, carbs: 30, fat: 13, defaultQty: 110 },

  // ── Asian / Indian / Mexican ──────────────────────────────────────────────
  { id: 'rice-fried', name: 'Fried Rice', aliases: ['chinese fried rice'], per: 'item', kcal: 480, protein: 14, carbs: 70, fat: 16, defaultQty: 350 },
  { id: 'rice-chicken-fried', name: 'Chicken Fried Rice', aliases: ['chicken fried rice'], per: 'item', kcal: 580, protein: 28, carbs: 70, fat: 18, defaultQty: 400 },
  { id: 'rice-egg-fried', name: 'Egg Fried Rice', aliases: ['egg fried rice'], per: 'item', kcal: 520, protein: 16, carbs: 72, fat: 17, defaultQty: 380 },
  { id: 'sushi-roll', name: 'Sushi Roll', aliases: ['california roll', 'sushi'], per: 'item', kcal: 250, protein: 9, carbs: 38, fat: 6, defaultQty: 180 },
  { id: 'sushi-nigiri', name: 'Sushi Nigiri', aliases: ['nigiri'], per: 'item', kcal: 50, protein: 4, carbs: 7, fat: 0.5, defaultQty: 25 },
  { id: 'sushi-sashimi', name: 'Sashimi', aliases: ['sashimi piece'], per: 'item', kcal: 35, protein: 7, carbs: 0, fat: 1, defaultQty: 20 },
  { id: 'ramen', name: 'Ramen', aliases: ['ramen noodles', 'ramen bowl'], per: 'item', kcal: 580, protein: 24, carbs: 80, fat: 18, defaultQty: 500 },
  { id: 'pad-thai', name: 'Pad Thai', aliases: ['pad thai', 'chicken pad thai'], per: 'item', kcal: 620, protein: 26, carbs: 76, fat: 22, defaultQty: 400 },
  { id: 'stir-fry', name: 'Stir Fry', aliases: ['vegetable stir fry', 'veggie stir fry'], per: 'item', kcal: 380, protein: 14, carbs: 48, fat: 14, defaultQty: 350 },
  { id: 'stir-fry-chicken', name: 'Chicken Stir Fry', aliases: ['chicken stir fry'], per: 'item', kcal: 520, protein: 32, carbs: 50, fat: 18, defaultQty: 400 },
  { id: 'stir-fry-beef', name: 'Beef Stir Fry', aliases: ['beef stir fry'], per: 'item', kcal: 540, protein: 30, carbs: 50, fat: 22, defaultQty: 400 },
  { id: 'curry-chicken', name: 'Chicken Curry', aliases: ['chicken curry'], per: 'item', kcal: 540, protein: 30, carbs: 38, fat: 26, defaultQty: 400 },
  { id: 'curry-beef', name: 'Beef Curry', aliases: ['beef curry'], per: 'item', kcal: 580, protein: 30, carbs: 38, fat: 30, defaultQty: 400 },
  { id: 'curry-vegetable', name: 'Vegetable Curry', aliases: ['veg curry', 'veggie curry'], per: 'item', kcal: 380, protein: 12, carbs: 50, fat: 14, defaultQty: 400 },
  { id: 'curry-butter-chicken', name: 'Butter Chicken', aliases: ['butter chicken curry'], per: 'item', kcal: 650, protein: 32, carbs: 28, fat: 42, defaultQty: 400 },
  { id: 'curry-tikka-masala', name: 'Chicken Tikka Masala', aliases: ['tikka masala'], per: 'item', kcal: 620, protein: 30, carbs: 30, fat: 38, defaultQty: 400 },
  { id: 'curry-lamb-rogan', name: 'Lamb Rogan Josh', aliases: ['rogan josh'], per: 'item', kcal: 580, protein: 32, carbs: 18, fat: 38, defaultQty: 400 },
  { id: 'curry-dal', name: 'Dal', aliases: ['lentil curry', 'dal curry'], per: 'item', kcal: 320, protein: 16, carbs: 44, fat: 8, defaultQty: 350 },
  { id: 'biryani-chicken', name: 'Chicken Biryani', aliases: ['biryani'], per: 'item', kcal: 680, protein: 32, carbs: 80, fat: 22, defaultQty: 450 },
  { id: 'naan', name: 'Naan Bread', aliases: ['naan'], per: 'item', kcal: 260, protein: 9, carbs: 45, fat: 5, defaultQty: 90 },
  { id: 'samosa', name: 'Samosa', aliases: ['samoosa'], per: 'item', kcal: 130, protein: 3, carbs: 14, fat: 7, defaultQty: 50 },
  { id: 'spring-roll', name: 'Spring Roll', aliases: ['spring rolls'], per: 'item', kcal: 110, protein: 3, carbs: 14, fat: 5, defaultQty: 50 },
  { id: 'dim-sum', name: 'Dim Sum', aliases: ['dumpling'], per: 'item', kcal: 60, protein: 3, carbs: 7, fat: 2, defaultQty: 30 },
  { id: 'taco-beef', name: 'Beef Taco', aliases: ['beef tacos', 'taco'], per: 'item', kcal: 220, protein: 12, carbs: 18, fat: 12, defaultQty: 90 },
  { id: 'taco-chicken', name: 'Chicken Taco', aliases: ['chicken tacos'], per: 'item', kcal: 200, protein: 14, carbs: 18, fat: 8, defaultQty: 90 },
  { id: 'burrito-beef', name: 'Beef Burrito', aliases: ['beef burrito'], per: 'item', kcal: 720, protein: 32, carbs: 78, fat: 30, defaultQty: 350 },
  { id: 'burrito-chicken', name: 'Chicken Burrito', aliases: ['chicken burrito'], per: 'item', kcal: 680, protein: 36, carbs: 80, fat: 22, defaultQty: 350 },
  { id: 'burrito-bowl', name: 'Burrito Bowl', aliases: ['chicken burrito bowl'], per: 'item', kcal: 620, protein: 38, carbs: 70, fat: 18, defaultQty: 450 },
  { id: 'nachos', name: 'Nachos', aliases: ['nacho', 'nachos plate'], per: 'item', kcal: 780, protein: 22, carbs: 78, fat: 42, defaultQty: 300 },
  { id: 'quesadilla', name: 'Quesadilla', aliases: ['cheese quesadilla'], per: 'item', kcal: 540, protein: 22, carbs: 42, fat: 30, defaultQty: 220 },
  { id: 'enchiladas', name: 'Enchiladas', aliases: ['enchilada'], per: 'item', kcal: 620, protein: 26, carbs: 56, fat: 30, defaultQty: 330 },

  // ── Salads ────────────────────────────────────────────────────────────────
  { id: 'salad-caesar', name: 'Caesar Salad', aliases: ['caesar', 'caesar salad'], per: 'item', kcal: 380, protein: 12, carbs: 18, fat: 28, defaultQty: 280 },
  { id: 'salad-chicken-caesar', name: 'Chicken Caesar Salad', aliases: ['chicken caesar'], per: 'item', kcal: 520, protein: 38, carbs: 20, fat: 32, defaultQty: 350 },
  { id: 'salad-greek', name: 'Greek Salad', aliases: ['greek salad'], per: 'item', kcal: 340, protein: 10, carbs: 16, fat: 26, defaultQty: 300 },
  { id: 'salad-cobb', name: 'Cobb Salad', aliases: ['cobb'], per: 'item', kcal: 520, protein: 32, carbs: 14, fat: 38, defaultQty: 380 },
  { id: 'salad-garden', name: 'Garden Salad', aliases: ['side salad', 'green salad'], per: 'item', kcal: 120, protein: 4, carbs: 14, fat: 5, defaultQty: 250 },
  { id: 'salad-chicken', name: 'Chicken Salad', aliases: ['grilled chicken salad'], per: 'item', kcal: 380, protein: 32, carbs: 14, fat: 22, defaultQty: 320 },
  { id: 'salad-tuna', name: 'Tuna Salad', aliases: ['tuna salad'], per: 'item', kcal: 360, protein: 28, carbs: 12, fat: 22, defaultQty: 300 },
  { id: 'salad-potato', name: 'Potato Salad', aliases: ['potato salad'], per: 'item', kcal: 260, protein: 4, carbs: 24, fat: 16, defaultQty: 200 },
  { id: 'salad-coleslaw', name: 'Coleslaw', aliases: ['coleslaw', 'cole slaw'], per: 'item', kcal: 180, protein: 2, carbs: 14, fat: 14, defaultQty: 120 },
  { id: 'salad-quinoa', name: 'Quinoa Salad', aliases: ['quinoa salad'], per: 'item', kcal: 380, protein: 14, carbs: 56, fat: 12, defaultQty: 300 },
  { id: 'salad-beetroot', name: 'Beetroot Salad', aliases: ['beet salad', 'beetroot salad'], per: 'item', kcal: 160, protein: 4, carbs: 24, fat: 6, defaultQty: 200 },

  // ── South African / Braai ─────────────────────────────────────────────────
  { id: 'sa-pap-wors', name: 'Pap & Wors', aliases: ['pap and wors', 'wors and pap'], per: 'item', kcal: 680, protein: 24, carbs: 68, fat: 32, defaultQty: 400 },
  { id: 'sa-bobotie', name: 'Bobotie', aliases: ['bobotie', 'sa bobotie'], per: 'item', kcal: 580, protein: 28, carbs: 36, fat: 32, defaultQty: 350 },
  { id: 'sa-chakalaka', name: 'Chakalaka', aliases: ['chakalaka relish'], per: 'item', kcal: 180, protein: 4, carbs: 20, fat: 8, defaultQty: 150 },
  { id: 'sa-vetkoek', name: 'Vetkoek', aliases: ['vetkoek', 'fat cake'], per: 'item', kcal: 320, protein: 6, carbs: 40, fat: 14, defaultQty: 100 },
  { id: 'sa-vetkoek-mince', name: 'Vetkoek & Mince', aliases: ['vetkoek and mince', 'mince vetkoek'], per: 'item', kcal: 560, protein: 22, carbs: 50, fat: 28, defaultQty: 250 },
  { id: 'sa-koeksister', name: 'Koeksister', aliases: ['koeksisters'], per: 'item', kcal: 250, protein: 2, carbs: 38, fat: 10, defaultQty: 60 },
  { id: 'sa-melktert', name: 'Melktert Slice', aliases: ['melktert', 'milk tart'], per: 'item', kcal: 290, protein: 5, carbs: 36, fat: 14, defaultQty: 100 },
  { id: 'sa-malva-pudding', name: 'Malva Pudding', aliases: ['malva'], per: 'item', kcal: 380, protein: 5, carbs: 58, fat: 14, defaultQty: 120 },
  { id: 'sa-gatsby', name: 'Gatsby', aliases: ['gatsby roll', 'cape town gatsby'], per: 'item', kcal: 1100, protein: 38, carbs: 110, fat: 56, defaultQty: 500 },
  { id: 'sa-roosterkoek', name: 'Roosterkoek', aliases: ['roosterkoek'], per: 'item', kcal: 240, protein: 6, carbs: 38, fat: 7, defaultQty: 90 },
  { id: 'sa-boboti-wrap', name: 'Bobotie Wrap', aliases: ['bobotie wrap'], per: 'item', kcal: 540, protein: 24, carbs: 56, fat: 24, defaultQty: 280 },
  { id: 'sa-braaibroodjie', name: 'Braaibroodjie', aliases: ['braai broodjie', 'braai sandwich'], per: 'item', kcal: 440, protein: 16, carbs: 38, fat: 24, defaultQty: 180 },
  { id: 'sa-potjiekos', name: 'Potjiekos', aliases: ['potjie'], per: 'item', kcal: 560, protein: 30, carbs: 40, fat: 28, defaultQty: 400 },
  { id: 'sa-tomato-bredie', name: 'Tomato Bredie', aliases: ['tamatie bredie', 'lamb tomato bredie'], per: 'item', kcal: 480, protein: 28, carbs: 22, fat: 30, defaultQty: 380 },
  { id: 'sa-frikkadel', name: 'Frikkadel', aliases: ['frikkadelle', 'meatball sa'], per: 'item', kcal: 110, protein: 8, carbs: 3, fat: 7, defaultQty: 60 },
  { id: 'sa-droewors-sticks', name: 'Droëwors Stick', aliases: ['droewors stick'], per: 'item', kcal: 60, protein: 4, carbs: 0, fat: 5, defaultQty: 12 },

  // ── Fast food chains ──────────────────────────────────────────────────────
  { id: 'kfc-streetwise-2', name: 'KFC Streetwise 2', aliases: ['streetwise 2', 'kfc streetwise two'], per: 'item', kcal: 720, protein: 36, carbs: 56, fat: 38, defaultQty: 350 },
  { id: 'kfc-zinger-burger', name: 'KFC Zinger Burger', aliases: ['zinger burger'], per: 'item', kcal: 560, protein: 26, carbs: 50, fat: 28, defaultQty: 220 },
  { id: 'kfc-twister', name: 'KFC Twister', aliases: ['twister wrap', 'kfc twister'], per: 'item', kcal: 600, protein: 24, carbs: 58, fat: 30, defaultQty: 270 },
  { id: 'kfc-piece-original', name: 'KFC Piece (Original)', aliases: ['kfc chicken piece', 'original recipe'], per: 'item', kcal: 270, protein: 22, carbs: 8, fat: 18, defaultQty: 110 },
  { id: 'mcd-bigmac-meal', name: 'McDonalds Big Mac Meal', aliases: ['big mac meal'], per: 'item', kcal: 1100, protein: 30, carbs: 130, fat: 50, defaultQty: 700 },
  { id: 'mcd-mcchicken', name: 'McChicken', aliases: ['mcchicken sandwich', 'mc chicken'], per: 'item', kcal: 400, protein: 14, carbs: 40, fat: 21, defaultQty: 145 },
  { id: 'mcd-fries-large', name: 'McDonalds Large Fries', aliases: ['mcdonalds large fries', 'large fries'], per: 'item', kcal: 510, protein: 7, carbs: 66, fat: 24, defaultQty: 154 },
  { id: 'mcd-fries-medium', name: 'McDonalds Medium Fries', aliases: ['medium fries', 'mcdonalds medium fries'], per: 'item', kcal: 340, protein: 4, carbs: 44, fat: 16, defaultQty: 117 },
  { id: 'mcd-mcflurry', name: 'McFlurry', aliases: ['oreo mcflurry'], per: 'item', kcal: 510, protein: 12, carbs: 80, fat: 16, defaultQty: 250 },
  { id: 'nandos-quarter', name: 'Nandos Quarter Chicken', aliases: ['nandos quarter', 'quarter chicken'], per: 'item', kcal: 280, protein: 36, carbs: 0, fat: 14, defaultQty: 200 },
  { id: 'nandos-half', name: 'Nandos Half Chicken', aliases: ['half chicken nandos'], per: 'item', kcal: 540, protein: 70, carbs: 0, fat: 28, defaultQty: 400 },
  { id: 'nandos-pita', name: 'Nandos Chicken Pita', aliases: ['nandos pita', 'chicken pita'], per: 'item', kcal: 480, protein: 32, carbs: 46, fat: 18, defaultQty: 280 },
  { id: 'steers-king-steer', name: 'Steers King Steer Burger', aliases: ['king steer', 'steers king'], per: 'item', kcal: 720, protein: 36, carbs: 52, fat: 38, defaultQty: 300 },
  { id: 'steers-rib-burger', name: 'Steers Rib Burger', aliases: ['rib burger steers', 'steers rib'], per: 'item', kcal: 680, protein: 28, carbs: 56, fat: 38, defaultQty: 280 },
  { id: 'wimpy-bacon-cheese', name: 'Wimpy Bacon Cheeseburger', aliases: ['wimpy burger', 'wimpy bacon cheese'], per: 'item', kcal: 660, protein: 30, carbs: 48, fat: 38, defaultQty: 270 },
  { id: 'subway-6-inch', name: 'Subway 6" Sub', aliases: ['subway sub', '6 inch sub', '6\" subway'], per: 'item', kcal: 420, protein: 24, carbs: 50, fat: 14, defaultQty: 240 },
  { id: 'subway-foot-long', name: 'Subway Footlong', aliases: ['footlong subway', 'subway footlong'], per: 'item', kcal: 800, protein: 46, carbs: 96, fat: 24, defaultQty: 470 },

  // ── Sides ─────────────────────────────────────────────────────────────────
  { id: 'side-fries', name: 'Chips / Fries', aliases: ['fries', 'french fries', 'slap chips', 'chips slap'], per: 'item', kcal: 380, protein: 4, carbs: 50, fat: 18, defaultQty: 150 },
  { id: 'side-fries-large', name: 'Large Chips', aliases: ['large chips', 'large fries', 'big fries'], per: 'item', kcal: 540, protein: 6, carbs: 72, fat: 25, defaultQty: 220 },
  { id: 'side-onion-rings', name: 'Onion Rings', aliases: ['onion ring'], per: 'item', kcal: 410, protein: 5, carbs: 50, fat: 22, defaultQty: 130 },
  { id: 'side-garlic-bread', name: 'Garlic Bread', aliases: ['garlic bread slice'], per: 'item', kcal: 150, protein: 4, carbs: 18, fat: 7, defaultQty: 40 },
  { id: 'side-mashed-potato', name: 'Mashed Potato', aliases: ['mash', 'mashed potatoes'], per: '100g', kcal: 113, protein: 2, carbs: 17, fat: 4 },
  { id: 'side-roast-potato', name: 'Roast Potatoes', aliases: ['roasted potatoes', 'roast potato'], per: '100g', kcal: 149, protein: 3, carbs: 26, fat: 4 },
  { id: 'side-baked-potato', name: 'Baked Potato', aliases: ['jacket potato', 'baked potato'], per: 'item', kcal: 220, protein: 5, carbs: 50, fat: 0.3, defaultQty: 200 },

  // ── Meat dishes ───────────────────────────────────────────────────────────
  { id: 'meat-roast-chicken', name: 'Roast Chicken Plate', aliases: ['roast chicken', 'roast chicken dinner'], per: 'item', kcal: 580, protein: 42, carbs: 40, fat: 26, defaultQty: 400 },
  { id: 'meat-grilled-chicken', name: 'Grilled Chicken Plate', aliases: ['grilled chicken plate'], per: 'item', kcal: 480, protein: 44, carbs: 38, fat: 14, defaultQty: 400 },
  { id: 'meat-chicken-rice', name: 'Chicken & Rice', aliases: ['chicken and rice plate', 'rice and chicken'], per: 'item', kcal: 540, protein: 38, carbs: 60, fat: 12, defaultQty: 400 },
  { id: 'meat-chicken-veg', name: 'Chicken & Vegetables', aliases: ['chicken and veg', 'chicken veggies'], per: 'item', kcal: 380, protein: 38, carbs: 22, fat: 14, defaultQty: 350 },
  { id: 'meat-steak-chips', name: 'Steak & Chips', aliases: ['steak and chips', 'steak chips'], per: 'item', kcal: 880, protein: 50, carbs: 70, fat: 40, defaultQty: 500 },
  { id: 'meat-steak-salad', name: 'Steak & Salad', aliases: ['steak salad', 'steak and salad'], per: 'item', kcal: 580, protein: 44, carbs: 14, fat: 38, defaultQty: 400 },
  { id: 'meat-mince-rice', name: 'Mince & Rice', aliases: ['mince and rice'], per: 'item', kcal: 620, protein: 30, carbs: 70, fat: 22, defaultQty: 400 },
  { id: 'meat-lamb-chops', name: 'Lamb Chops', aliases: ['lamb chops plate'], per: 'item', kcal: 540, protein: 36, carbs: 4, fat: 40, defaultQty: 250 },
  { id: 'meat-pork-chop-plate', name: 'Pork Chop Plate', aliases: ['pork chop plate'], per: 'item', kcal: 540, protein: 38, carbs: 36, fat: 26, defaultQty: 400 },
  { id: 'meat-chicken-wings', name: 'Chicken Wings (6)', aliases: ['wings', 'chicken wings'], per: 'item', kcal: 520, protein: 38, carbs: 6, fat: 38, defaultQty: 250 },
  { id: 'meat-chicken-wing', name: 'Chicken Wing', aliases: ['wing'], per: 'item', kcal: 90, protein: 6, carbs: 1, fat: 6, defaultQty: 45 },
  { id: 'meat-chicken-drumstick', name: 'Chicken Drumstick', aliases: ['drumstick'], per: 'item', kcal: 120, protein: 14, carbs: 0, fat: 7, defaultQty: 75 },
  { id: 'meat-meatballs', name: 'Meatballs (5)', aliases: ['meatballs', 'spaghetti meatballs'], per: 'item', kcal: 380, protein: 24, carbs: 6, fat: 28, defaultQty: 180 },

  // ── Fish dishes ───────────────────────────────────────────────────────────
  { id: 'fish-and-chips', name: 'Fish & Chips', aliases: ['fish and chips'], per: 'item', kcal: 820, protein: 32, carbs: 84, fat: 38, defaultQty: 450 },
  { id: 'fish-grilled-hake', name: 'Grilled Hake', aliases: ['grilled hake', 'hake plate'], per: 'item', kcal: 320, protein: 30, carbs: 22, fat: 12, defaultQty: 300 },
  { id: 'fish-grilled-salmon', name: 'Grilled Salmon Plate', aliases: ['grilled salmon plate'], per: 'item', kcal: 540, protein: 38, carbs: 30, fat: 26, defaultQty: 350 },
  { id: 'fish-cakes', name: 'Fishcakes', aliases: ['fish cakes', 'fishcake'], per: 'item', kcal: 180, protein: 10, carbs: 15, fat: 9, defaultQty: 80 },
  { id: 'fish-calamari', name: 'Calamari', aliases: ['fried calamari', 'calamari rings'], per: 'item', kcal: 380, protein: 22, carbs: 24, fat: 22, defaultQty: 200 },
  { id: 'fish-prawns', name: 'Prawns Plate', aliases: ['prawns', 'grilled prawns'], per: 'item', kcal: 380, protein: 30, carbs: 18, fat: 20, defaultQty: 250 },

  // ── Soup ──────────────────────────────────────────────────────────────────
  { id: 'soup-tomato', name: 'Tomato Soup', aliases: ['tomato soup'], per: 'item', kcal: 160, protein: 4, carbs: 24, fat: 5, defaultQty: 300 },
  { id: 'soup-chicken-noodle', name: 'Chicken Noodle Soup', aliases: ['chicken noodle soup'], per: 'item', kcal: 220, protein: 16, carbs: 28, fat: 5, defaultQty: 350 },
  { id: 'soup-butternut', name: 'Butternut Soup', aliases: ['butternut soup'], per: 'item', kcal: 220, protein: 4, carbs: 36, fat: 8, defaultQty: 300 },
  { id: 'soup-minestrone', name: 'Minestrone', aliases: ['minestrone soup'], per: 'item', kcal: 240, protein: 10, carbs: 36, fat: 6, defaultQty: 350 },
  { id: 'soup-pumpkin', name: 'Pumpkin Soup', aliases: ['pumpkin soup'], per: 'item', kcal: 200, protein: 4, carbs: 30, fat: 7, defaultQty: 300 },
  { id: 'soup-beef-vegetable', name: 'Beef & Vegetable Soup', aliases: ['beef veg soup'], per: 'item', kcal: 280, protein: 18, carbs: 30, fat: 8, defaultQty: 350 },

  // ── Snacks ────────────────────────────────────────────────────────────────
  { id: 'snack-popcorn-bowl', name: 'Bowl of Popcorn', aliases: ['popcorn', 'popcorn bowl'], per: 'item', kcal: 250, protein: 7, carbs: 38, fat: 11, defaultQty: 50 },
  { id: 'snack-trail-mix', name: 'Trail Mix Handful', aliases: ['trail mix'], per: 'item', kcal: 180, protein: 5, carbs: 16, fat: 11, defaultQty: 30 },
  { id: 'snack-cheese-crackers', name: 'Cheese & Crackers', aliases: ['cheese crackers', 'cheese and crackers'], per: 'item', kcal: 280, protein: 12, carbs: 22, fat: 16, defaultQty: 80 },
  { id: 'snack-hummus-pita', name: 'Hummus & Pita', aliases: ['hummus pita', 'hummus and pita'], per: 'item', kcal: 340, protein: 11, carbs: 46, fat: 12, defaultQty: 140 },
  { id: 'snack-rice-cakes', name: 'Rice Cakes', aliases: ['rice cake'], per: 'item', kcal: 35, protein: 0.7, carbs: 7.3, fat: 0.3, defaultQty: 9 },
  { id: 'snack-nuts-handful', name: 'Handful of Nuts', aliases: ['nuts handful', 'handful nuts'], per: 'item', kcal: 170, protein: 5, carbs: 6, fat: 15, defaultQty: 28 },
  { id: 'snack-dark-choc-square', name: 'Dark Chocolate Square', aliases: ['choc square', 'dark choc square'], per: 'item', kcal: 60, protein: 1, carbs: 5, fat: 4, defaultQty: 10 },
  { id: 'snack-protein-shake-scoop', name: 'Whey Scoop', aliases: ['whey scoop', 'protein scoop'], per: 'item', kcal: 120, protein: 24, carbs: 3, fat: 2, defaultQty: 30 },

  // ── Drinks ────────────────────────────────────────────────────────────────
  { id: 'drink-cappuccino', name: 'Cappuccino', aliases: ['cappuccino'], per: 'item', kcal: 80, protein: 5, carbs: 8, fat: 4, defaultQty: 240 },
  { id: 'drink-latte', name: 'Latte', aliases: ['cafe latte'], per: 'item', kcal: 150, protein: 8, carbs: 14, fat: 7, defaultQty: 350 },
  { id: 'drink-flat-white', name: 'Flat White', aliases: ['flat white'], per: 'item', kcal: 130, protein: 8, carbs: 11, fat: 6, defaultQty: 220 },
  { id: 'drink-americano', name: 'Americano', aliases: ['black coffee americano'], per: 'item', kcal: 5, protein: 0.3, carbs: 1, fat: 0, defaultQty: 240 },
  { id: 'drink-mocha', name: 'Mocha', aliases: ['caffè mocha'], per: 'item', kcal: 290, protein: 9, carbs: 35, fat: 12, defaultQty: 350 },
  { id: 'drink-frappe', name: 'Frappuccino', aliases: ['frappe', 'frappucino'], per: 'item', kcal: 340, protein: 6, carbs: 56, fat: 11, defaultQty: 470 },
  { id: 'drink-hot-choc', name: 'Hot Chocolate', aliases: ['hot chocolate', 'hot choc'], per: 'item', kcal: 260, protein: 10, carbs: 38, fat: 8, defaultQty: 300 },
  { id: 'drink-tea-milk', name: 'Tea with Milk', aliases: ['cup of tea', 'milky tea'], per: 'item', kcal: 30, protein: 1.5, carbs: 4, fat: 1, defaultQty: 240 },
  { id: 'drink-coke', name: 'Coca-Cola (Can)', aliases: ['coke can', 'coca cola can', 'coke'], per: 'item', kcal: 139, protein: 0, carbs: 39, fat: 0, defaultQty: 330 },
  { id: 'drink-coke-zero', name: 'Coke Zero (Can)', aliases: ['coke zero', 'diet coke'], per: 'item', kcal: 1, protein: 0, carbs: 0, fat: 0, defaultQty: 330 },
  { id: 'drink-sprite', name: 'Sprite (Can)', aliases: ['sprite'], per: 'item', kcal: 139, protein: 0, carbs: 38, fat: 0, defaultQty: 330 },
  { id: 'drink-fanta', name: 'Fanta (Can)', aliases: ['fanta orange'], per: 'item', kcal: 160, protein: 0, carbs: 42, fat: 0, defaultQty: 330 },
  { id: 'drink-redbull', name: 'Red Bull', aliases: ['red bull can'], per: 'item', kcal: 112, protein: 1, carbs: 27, fat: 0, defaultQty: 250 },
  { id: 'drink-monster', name: 'Monster Energy', aliases: ['monster can', 'monster energy'], per: 'item', kcal: 220, protein: 0, carbs: 54, fat: 0, defaultQty: 500 },
  { id: 'drink-juice-glass', name: 'Glass of Juice', aliases: ['juice glass', 'fruit juice'], per: 'item', kcal: 110, protein: 1, carbs: 26, fat: 0.3, defaultQty: 240 },
  { id: 'drink-milkshake', name: 'Milkshake', aliases: ['milkshake', 'choc milkshake'], per: 'item', kcal: 480, protein: 12, carbs: 70, fat: 18, defaultQty: 400 },
  { id: 'drink-smoothie-fruit', name: 'Fruit Smoothie', aliases: ['fruit smoothie', 'smoothie'], per: 'item', kcal: 240, protein: 6, carbs: 50, fat: 2, defaultQty: 400 },
  { id: 'drink-beer-pint', name: 'Beer Pint', aliases: ['beer', 'pint of beer'], per: 'item', kcal: 200, protein: 2, carbs: 17, fat: 0, defaultQty: 568 },
  { id: 'drink-beer-bottle', name: 'Beer Bottle (340ml)', aliases: ['beer bottle', 'castle lager', 'black label', 'savanna'], per: 'item', kcal: 145, protein: 1.2, carbs: 11, fat: 0, defaultQty: 340 },
  { id: 'drink-wine-glass', name: 'Glass of Wine', aliases: ['wine glass', 'wine', 'red wine glass'], per: 'item', kcal: 125, protein: 0.1, carbs: 4, fat: 0, defaultQty: 150 },
  { id: 'drink-spirit-shot', name: 'Spirit Shot', aliases: ['vodka shot', 'whisky shot', 'gin shot', 'shot of vodka', 'shot of whisky'], per: 'item', kcal: 64, protein: 0, carbs: 0, fat: 0, defaultQty: 30 },
  { id: 'drink-gin-tonic', name: 'Gin & Tonic', aliases: ['gin tonic', 'g and t'], per: 'item', kcal: 140, protein: 0, carbs: 10, fat: 0, defaultQty: 200 },

  // ── Desserts ──────────────────────────────────────────────────────────────
  { id: 'dessert-icecream-scoop', name: 'Ice Cream Scoop', aliases: ['ice cream', 'ice-cream'], per: 'item', kcal: 140, protein: 2, carbs: 17, fat: 7, defaultQty: 65 },
  { id: 'dessert-icecream-cone', name: 'Ice Cream Cone', aliases: ['ice cream cone', '99'], per: 'item', kcal: 280, protein: 4, carbs: 36, fat: 13, defaultQty: 140 },
  { id: 'dessert-cheesecake-slice', name: 'Cheesecake Slice', aliases: ['cheesecake'], per: 'item', kcal: 420, protein: 7, carbs: 35, fat: 28, defaultQty: 125 },
  { id: 'dessert-choc-cake', name: 'Chocolate Cake Slice', aliases: ['chocolate cake', 'choc cake'], per: 'item', kcal: 380, protein: 5, carbs: 50, fat: 18, defaultQty: 110 },
  { id: 'dessert-carrot-cake', name: 'Carrot Cake Slice', aliases: ['carrot cake'], per: 'item', kcal: 390, protein: 5, carbs: 51, fat: 19, defaultQty: 110 },
  { id: 'dessert-brownie', name: 'Brownie', aliases: ['choc brownie', 'chocolate brownie'], per: 'item', kcal: 280, protein: 4, carbs: 36, fat: 14, defaultQty: 80 },
  { id: 'dessert-cookie', name: 'Cookie', aliases: ['chocolate chip cookie', 'choc chip cookie'], per: 'item', kcal: 160, protein: 2, carbs: 22, fat: 7, defaultQty: 30 },
  { id: 'dessert-donut', name: 'Doughnut', aliases: ['donut', 'doughnuts'], per: 'item', kcal: 250, protein: 3, carbs: 31, fat: 13, defaultQty: 65 },
  { id: 'dessert-muffin-choc', name: 'Chocolate Muffin', aliases: ['choc muffin'], per: 'item', kcal: 380, protein: 5, carbs: 50, fat: 17, defaultQty: 110 },
  { id: 'dessert-muffin-blueberry', name: 'Blueberry Muffin', aliases: ['blueberry muffin'], per: 'item', kcal: 350, protein: 5, carbs: 50, fat: 14, defaultQty: 110 },
  { id: 'dessert-tiramisu', name: 'Tiramisu', aliases: ['tiramisu slice'], per: 'item', kcal: 380, protein: 6, carbs: 38, fat: 22, defaultQty: 120 },
  { id: 'dessert-pudding-stickytoffee', name: 'Sticky Toffee Pudding', aliases: ['sticky toffee'], per: 'item', kcal: 480, protein: 5, carbs: 70, fat: 18, defaultQty: 130 },
  { id: 'dessert-trifle', name: 'Trifle', aliases: ['trifle bowl'], per: 'item', kcal: 320, protein: 5, carbs: 42, fat: 14, defaultQty: 150 },
  { id: 'dessert-fruit-salad', name: 'Fruit Salad Bowl', aliases: ['fruit salad'], per: 'item', kcal: 130, protein: 2, carbs: 33, fat: 0.4, defaultQty: 220 },

  // ── Chocolates / Candy ────────────────────────────────────────────────────
  { id: 'choc-bar-snickers', name: 'Snickers', aliases: ['snickers bar'], per: 'item', kcal: 250, protein: 4, carbs: 33, fat: 12, defaultQty: 50 },
  { id: 'choc-bar-marsbar', name: 'Mars Bar', aliases: ['mars'], per: 'item', kcal: 230, protein: 2, carbs: 36, fat: 9, defaultQty: 51 },
  { id: 'choc-bar-twix', name: 'Twix', aliases: ['twix bar'], per: 'item', kcal: 250, protein: 2, carbs: 33, fat: 12, defaultQty: 50 },
  { id: 'choc-bar-kitkat', name: 'KitKat', aliases: ['kit kat'], per: 'item', kcal: 210, protein: 3, carbs: 25, fat: 11, defaultQty: 42 },
  { id: 'choc-bar-lunchbar', name: 'Lunch Bar', aliases: ['lunchbar'], per: 'item', kcal: 230, protein: 3, carbs: 26, fat: 13, defaultQty: 48 },
  { id: 'choc-bar-bar-one', name: 'Bar One', aliases: ['bar-one'], per: 'item', kcal: 220, protein: 3, carbs: 32, fat: 9, defaultQty: 50 },
  { id: 'choc-tex', name: 'Tex Bar', aliases: ['tex'], per: 'item', kcal: 215, protein: 3, carbs: 27, fat: 11, defaultQty: 45 },
  { id: 'choc-dairymilk-slab', name: 'Cadbury Dairy Milk Slab (small)', aliases: ['dairy milk slab', 'dairy milk small'], per: 'item', kcal: 480, protein: 6, carbs: 56, fat: 26, defaultQty: 80 },
  { id: 'choc-aero', name: 'Aero Bar', aliases: ['aero'], per: 'item', kcal: 200, protein: 2.5, carbs: 22, fat: 11, defaultQty: 36 },

  // ── Bakery ────────────────────────────────────────────────────────────────
  { id: 'bakery-pie-steak', name: 'Steak Pie', aliases: ['steak pie'], per: 'item', kcal: 460, protein: 14, carbs: 36, fat: 28, defaultQty: 180 },
  { id: 'bakery-pie-chicken', name: 'Chicken Pie', aliases: ['chicken pie'], per: 'item', kcal: 420, protein: 16, carbs: 36, fat: 24, defaultQty: 180 },
  { id: 'bakery-pie-pepper', name: 'Pepper Steak Pie', aliases: ['pepper steak pie', 'pepper pie'], per: 'item', kcal: 470, protein: 16, carbs: 36, fat: 28, defaultQty: 180 },
  { id: 'bakery-cornish', name: 'Cornish Pasty', aliases: ['cornish pasty'], per: 'item', kcal: 450, protein: 12, carbs: 38, fat: 28, defaultQty: 200 },
  { id: 'bakery-sausage-roll', name: 'Sausage Roll', aliases: ['sausage roll'], per: 'item', kcal: 290, protein: 8, carbs: 22, fat: 19, defaultQty: 90 },
  { id: 'bakery-scone', name: 'Scone', aliases: ['scone', 'plain scone'], per: 'item', kcal: 220, protein: 5, carbs: 32, fat: 8, defaultQty: 60 },
  { id: 'bakery-bagel', name: 'Bagel (plain)', aliases: ['plain bagel'], per: 'item', kcal: 270, protein: 11, carbs: 53, fat: 1.5, defaultQty: 100 },
  { id: 'bakery-pretzel', name: 'Soft Pretzel', aliases: ['pretzel'], per: 'item', kcal: 380, protein: 11, carbs: 80, fat: 3, defaultQty: 115 },
]
