export const QUOTES = [
  { text: "Discipline is choosing between what you want now and what you want most.", author: "Abraham Lincoln" },
  { text: "The body achieves what the mind believes.", author: "Unknown" },
  { text: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
  { text: "Don't wish it were easier. Wish you were better.", author: "Jim Rohn" },
  { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
  { text: "The pain you feel today will be the strength you feel tomorrow.", author: "Arnold Schwarzenegger" },
  { text: "Champions aren't made in gyms. Champions are made from something they have deep inside them.", author: "Muhammad Ali" },
  { text: "If it doesn't challenge you, it doesn't change you.", author: "Fred DeVito" },
  { text: "Strength does not come from the body. It comes from the will of the soul.", author: "Mahatma Gandhi" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "I can do all things through Christ who strengthens me.", author: "Philippians 4:13" },
  { text: "Be strong and courageous. Do not be frightened or dismayed, for the Lord your God is with you.", author: "Joshua 1:9" },
  { text: "Commit to the Lord whatever you do, and he will establish your plans.", author: "Proverbs 16:3" },
  { text: "For I know the plans I have for you, plans to prosper you and not to harm you.", author: "Jeremiah 29:11" },
  { text: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
  { text: "Your future self is watching you right now through your memories.", author: "Aubrey Marcus" },
  { text: "Every rep is a vote for the person you're becoming.", author: "James Clear" },
  { text: "Don't count the days. Make the days count.", author: "Muhammad Ali" },
  { text: "The difference between who you are and who you want to be is what you do.", author: "Unknown" },
  { text: "Motivation gets you started. Discipline keeps you going.", author: "Unknown" },
  { text: "Track actions, not motivation. Daily wins compound.", author: "Life OS" },
  { text: "One more rep. One more set. One more day.", author: "The Grind" },
  { text: "Train hard. Eat clean. Sleep more. Repeat.", author: "Unknown" },
  { text: "The iron never lies to you.", author: "Henry Rollins" },
  { text: "Embrace the struggle and let it make you stronger.", author: "Unknown" },
  { text: "Small progress is still progress.", author: "Unknown" },
  { text: "Be the hardest worker in the room.", author: "Dwayne Johnson" },
  { text: "Today's pain is tomorrow's power.", author: "Unknown" },
  { text: "Don't stop when you're tired. Stop when you're done.", author: "Unknown" },
  { text: "The grind doesn't stop. Neither do I.", author: "Unknown" },
  { text: "Every morning is a second chance.", author: "Unknown" },
  { text: "6:30 AM. While the world sleeps, you build.", author: "Life OS" },
  { text: "Your body can stand almost anything. It's your mind you have to convince.", author: "Unknown" },
  { text: "Work in silence. Let success make the noise.", author: "Unknown" },
  { text: "Build the life you can't stop thinking about.", author: "Unknown" },
  { text: "Consistency is what transforms average into excellence.", author: "Unknown" },
  { text: "The will to win means nothing without the will to prepare.", author: "Juma Ikangaa" },
  { text: "Prove yourself to yourself, not to others.", author: "Unknown" },
  { text: "You are what you repeatedly do. Excellence is a habit.", author: "Aristotle" },
  { text: "Faith without works is dead.", author: "James 2:26" },
  { text: "Run in such a way as to get the prize.", author: "1 Corinthians 9:24" },
  { text: "Whatever you do, work at it with all your heart.", author: "Colossians 3:23" },
  { text: "The Lord is my strength and my shield.", author: "Psalm 28:7" },
  { text: "Lift heavy. Pray hard. Sleep 8. Repeat.", author: "Life OS" },
  { text: "Cape Town doesn't build weak men.", author: "Life OS" },
  { text: "At 19, you're not behind. You're early.", author: "Life OS" },
  { text: "78kg today. Watch what's coming.", author: "Life OS" },
  { text: "Business, body, belief. Build all three.", author: "Life OS" },
  { text: "Every 10k steps is a vote for your future self.", author: "Life OS" },
  { text: "Protein, purpose, prayer. That's the stack.", author: "Life OS" },
  { text: "No shortcuts. Just reps and grace.", author: "Life OS" },
  { text: "Earn your rest. Rest with gratitude.", author: "Life OS" },
  { text: "The mirror shows today. The charts show tomorrow.", author: "Life OS" },
  { text: "More water. More sleep. More grateful.", author: "Life OS" },
  { text: "A man who controls his body controls his life.", author: "Unknown" },
  { text: "Grow your business like you grow your muscle: with patience and progressive overload.", author: "Life OS" },
  { text: "Stillness is not laziness. Recovery is work.", author: "Life OS" },
  { text: "God first. Then everything else follows.", author: "Life OS" },
  { text: "The system works if you work the system.", author: "Life OS" },
  { text: "19 years old with a life OS. That's rare.", author: "Life OS" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
]

export function getDailyQuote(dateStr?: string): typeof QUOTES[0] {
  const seed = dateStr ?? new Date().toISOString().slice(0, 10)
  const hash = seed.split('').reduce((acc, c) => acc + c.charCodeAt(0), 0)
  return QUOTES[hash % QUOTES.length]
}
