import type { Goal, WeeklyGoal, Lift, UserSettings, TimerPreset } from '@/types'

export const DEFAULT_SETTINGS: UserSettings = {
  name: 'Janco',
  wakeTime: '06:30',
  height: 175,
  startingWeight: 78,
  schedule: {
    monday: 'calisthenics',
    tuesday: 'weights',
    wednesday: 'weights',
    thursday: 'weights',
    friday: 'calisthenics',
    saturday: 'optional-cardio',
    sunday: 'rest',
  },
  targets: {
    kcal: 2900,
    protein: 170,
    carbs: 350,
    fat: 78,
    waterL: 2.5,
    steps: 10000,
    sleepH: 8,
  },
  timerSound: true,
  timerVibration: true,
  reducedMotion: false,
  profile: undefined,
  goalSentence: '',
  autoTargets: false,
}

export const DEFAULT_GOALS: Goal[] = [
  {
    id: 'goal-wake',
    title: 'Wake up by 6:30 AM',
    category: 'discipline',
    color: '#FFB020',
    cadence: 'daily',
    active: true,
    createdAt: new Date().toISOString(),
    order: 0,
  },
  {
    id: 'goal-sleep',
    title: '8 hours sleep',
    category: 'recovery',
    color: '#7A5CFF',
    cadence: 'daily',
    targetValue: 8,
    unit: 'hrs',
    active: true,
    createdAt: new Date().toISOString(),
    order: 1,
  },
  {
    id: 'goal-water',
    title: 'Drink 2.5L water',
    category: 'fitness',
    color: '#00E5FF',
    cadence: 'daily',
    targetValue: 2.5,
    unit: 'L',
    active: true,
    createdAt: new Date().toISOString(),
    order: 2,
  },
  {
    id: 'goal-steps',
    title: 'Hit 10k steps',
    category: 'fitness',
    color: '#C6FF3D',
    cadence: 'daily',
    targetValue: 10000,
    unit: 'steps',
    active: true,
    createdAt: new Date().toISOString(),
    order: 3,
  },
  {
    id: 'goal-workout',
    title: 'Complete assigned workout',
    category: 'fitness',
    color: '#FF2D87',
    cadence: 'daily',
    schedule: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'],
    active: true,
    createdAt: new Date().toISOString(),
    order: 4,
  },
  {
    id: 'goal-faith',
    title: 'Faith / devotional time',
    category: 'faith',
    color: '#FFB020',
    cadence: 'daily',
    active: true,
    createdAt: new Date().toISOString(),
    order: 5,
  },
  {
    id: 'goal-business',
    title: 'Business work completed',
    category: 'business',
    color: '#C026FF',
    cadence: 'daily',
    active: true,
    createdAt: new Date().toISOString(),
    order: 6,
  },
]

export const DEFAULT_WEEKLY_GOALS: WeeklyGoal[] = [
  {
    id: 'weekly-jog',
    title: '1× Jog session',
    color: '#00E5FF',
    targetCount: 1,
    active: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'weekly-sprint',
    title: '1× Sprint session',
    color: '#FF2D87',
    targetCount: 1,
    active: true,
    createdAt: new Date().toISOString(),
  },
]

export const DEFAULT_LIFTS: Lift[] = [
  { id: 'lift-bench', name: 'Bench Press', unit: 'kg', category: 'barbell', active: true, createdAt: new Date().toISOString() },
  { id: 'lift-squat', name: 'Squat', unit: 'kg', category: 'barbell', active: true, createdAt: new Date().toISOString() },
  { id: 'lift-deadlift', name: 'Deadlift', unit: 'kg', category: 'barbell', active: true, createdAt: new Date().toISOString() },
  { id: 'lift-pullups', name: 'Pull-ups', unit: 'reps', category: 'bodyweight', active: true, createdAt: new Date().toISOString() },
  { id: 'lift-ohp', name: 'Overhead Press', unit: 'kg', category: 'barbell', active: true, createdAt: new Date().toISOString() },
  { id: 'lift-row', name: 'Barbell Row', unit: 'kg', category: 'barbell', active: true, createdAt: new Date().toISOString() },
]

export const DEFAULT_TIMER_PRESETS: TimerPreset[] = [
  { id: 'preset-25', label: 'Focus 25', seconds: 25 * 60, color: '#FF2D87' },
  { id: 'preset-50', label: 'Deep Work 50', seconds: 50 * 60, color: '#C026FF' },
  { id: 'preset-90', label: 'Flow State 90', seconds: 90 * 60, color: '#7A5CFF' },
  { id: 'preset-rest60', label: 'Rest 60s', seconds: 60, color: '#00E5FF' },
  { id: 'preset-rest90', label: 'Rest 90s', seconds: 90, color: '#00E5FF' },
  { id: 'preset-rest120', label: 'Rest 2min', seconds: 120, color: '#C6FF3D' },
  { id: 'preset-rest180', label: 'Rest 3min', seconds: 180, color: '#FFB020' },
]
